In [3]:
import numpy as np

In [6]:
listarray = np.array([[1,2,3], [5,8,6], [5,2,8]])

In [7]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [5, 2, 8]])

In [6]:
listarray.dtype

dtype('int32')

In [5]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

In [10]:
np.array({31,23,23})

array({31, 23}, dtype=object)

In [11]:
zeros = np.zeros((2, 5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.dtype

dtype('float64')

In [14]:
zeros.shape

(2, 5)

In [15]:
zeros.size

10

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,4,10)

In [19]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [20]:
lspacee = np.linspace(1,4,4)

In [21]:
lspacee

array([1., 2., 3., 4.])

**creates an empty list of random value**

In [22]:
emp = np.empty((4,6))  

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037657e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 6.23053954e-307,
        7.56602523e-307, 8.90095411e-307, 2.56765117e-312]])

**purani ek lspace naam ki array ke size ki empty array bana di**

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

**creates an identity matrix**

In [27]:
ide = np.identity(15)

In [28]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [29]:
ide.shape

(15, 15)

In [30]:
ide.size

225

**we can reshape an array but only if the reshape array consist same number of elements as the previous array**

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**makes an array straight or 1D**

In [40]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**CONCEPT OF AXIS IN NUMPY**

**AXIS-0 ARROW IS DOWNWAYS AND AXIS-1 IS UPWAYS**

In [41]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [42]:
arr = np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis=0)

array([12,  8,  9])

In [45]:
arr.sum(axis=1)

array([ 6, 15,  8])

**T=TRANSPOSE ROW COLUMN BAN JAEGI COLUMN ROW**

In [47]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [49]:
arr.flat

In [50]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
arr.ndim

2

In [54]:
arr.nbytes

36

In [57]:
import numpy as np

In [58]:
one = np.array([1,2,3,4444,55,655])

In [59]:
one.argmax()

3

In [60]:
one.argmin()

0

In [61]:
one.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
arr.argmin()

8

In [67]:
arr.argmax()

6

In [69]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [70]:
arr.argmin(axis=0)

array([0, 0, 2], dtype=int64)

In [71]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [72]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

**MATHEMATICAL OPERATIONS**

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
arr2 = ([[1, 2, 4],
       [4, 3, 2],
       [2, 1, 0]])

In [75]:
arr2

[[1, 2, 4], [4, 3, 2], [2, 1, 0]]

In [76]:
arr + arr2

array([[2, 4, 7],
       [8, 8, 8],
       [9, 2, 0]])

In [77]:
arr * arr2

array([[ 1,  4, 12],
       [16, 15, 12],
       [14,  1,  0]])

In [79]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [80]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [85]:
np.count_nonzero(arr)

8

In [86]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [ ]:
arr[1,2]=0

In [88]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

**BELOW IS THE PROOF THAT NUMPY USE LESS STORAGE**

In [89]:
import sys

In [94]:
py_ar = [0,4,55,2]

In [95]:
np_ar = np.array(py_ar)

In [96]:
sys.getsizeof(1) * len(py_ar)

112

In [97]:
np_ar.itemsize * np_ar.size

16

In [98]:
np_ar.tolist()

[0, 4, 55, 2]